# -*- coding: utf-8 -*-
"""appss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPW8dIIEVGTK08gJstvjoyXMluQFtkfR
"""

#!pip install streamlit
#!pip install deep_translator

import streamlit as st
import pandas as pd
import random
import joblib

pipeline = joblib.load("sentiment.pkl")


st.title(" SENTIMENT ANALYSIS APP ")

product_name = st.text_input("Enter Product Name")
text_input = st.text_area("Enter your review or comment:")
if st.button("Predict Sentiment"):
    if text_input.strip():
        with st.spinner("Translating and analyzing sentiment..."):
            prediction = pipeline.predict(pd.Series([text_input]))[0]
            if prediction.lower() == "positive":
                color = "green"
                emoji = "😊"
                auto_rating = random.choice([4, 5])
                message = "🎉 Thank you for the valuable feedback on this product!"
                st.balloons()

            elif prediction.lower() == "negative":
                color = "red"
                emoji = "😡"
                auto_rating = random.choice([1, 2])
                message = "😢 Ohh sorry! We'll work on improving this product."
                st.error("We're sorry to hear that 😔")

            else:
                color = "orange"
                emoji = "😐"
                auto_rating = 3
                message = "🤝 Ohh, we'll try to improve this product for you!"
                st.warning("Your feedback helps us get better!")

        st.markdown(f"### 🛍️ Product: **{product_name if product_name else 'N/A'}**")
        st.markdown(f"### 🤖 Auto Rating : {'⭐' * auto_rating}")

        # CLEAN LINE (NO U+00A0)
        st.markdown(
            f"<h3 style='color:{color};'>Predicted Sentiment: {emoji} {prediction}</h3>",
            unsafe_allow_html=True
        )

        st.write(f"### 📊 Sentiment: **{prediction.upper()}**")
        st.success(message)

    else:
        st.warning("Please enter some text.")


